[project]
name = "quantist_api"
version = "1.1.0"
description = "Backend of Quantist.io"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]==0.141.1",
    "google-cloud-bigquery-storage==2.41.0",
    "google-cloud-bigquery==3.45.2",
    "jinja2==3.1.6",
    "kaleido==1.4.0",
    "orjson==3.12.0",
    "pandas[performance]==3.0.5",
    "plotly==7.1.0",
    "polars==1.44.2",
    "pyarrow==25.0.1",
    "python-dotenv==1.2.3",
    "scikit-learn==1.9.1",
    "sqlalchemy==2.0.54",
    "sqlalchemy-bigquery==1.17.2",
    "uvicorn[standard]==0.53.0",
]

[project.optional-dependencies]
dev = [
    "pytest==9.1.1",
    "requests==2.34.2",
    "ruff==0.16.8",
]
server = [
    "psycopg[binary]==3.3.5",
]
